model: "MLP_MC21"
dataset:
  data_path: ../data/mc21_isabela_qt_2sigma_restriction/electron_ringer.parquet
  rings_col: "TrigEMClusterContainer.ringsE"
  et_col: "TrigEMClusterContainer.et"
  eta_col: "TrigEMClusterContainer.eta"
  label_col: target
max_epochs: 5000
batch_size: 1024
learning_rate: 0.001
patience: 50
n_splits: 5
n_inits: 5
seed: 42
